### ISSUE TITLE
Email layout

### ISSUE THREAD

**Issue by AValintsev** [noBugsException/ChelseaBoots#12]

**Comment by digitalLeaderAuthor** [comment]
https://ua.godaddy.com/help/configuring-email-with-nopcommerce-5620

**Comment by digitalLeaderAuthor** [comment]
![image](https://cloud.githubusercontent.com/assets/19479619/21471762/bfacd734-cac5-11e6-9d74-f9e60b494639.png)

**Comment by AValintsev** [comment]
Не шлет почту кроме gmail. Похоже что это ошибка хостинга

**Comment by AValintsev** [comment]
Ребята написали следующее:
Протестировали пересылку писем, на ukr.net письма доходят. 
Используйте в настройках сайта сервер localhost, 25 порт и учетные данные почтового ящика отправителя.
