### ISSUE TITLE
Language and html on Checkout page Step 4

### ISSUE THREAD

**Issue by digitalLeaderAuthor** [noBugsException/ChelseaBoots#29]
![image](https://cloud.githubusercontent.com/assets/19479619/21523935/eaa06ca6-cd1a-11e6-97ab-01e0214c15c5.png)

**Comment by AValintsev** [comment]
the plugin must to be changed to support multilanguage

**Comment by AValintsev** [comment]
Конфигурация - ПЛатежи - Способы оплаты - PayInStore
После нужно скинуть кеш

ru: Полсе поступения заказа, с Вами свяжеться наш менеджер, выяснит все детали по заказу, и, вышлет Вам смс для перевода средств на карту Приватбанка.
ua: Після надходження замовлення, з Вами зв'яжеться наш менеджер, з'ясує усі деталі, та відішле Вам смс із даними для переводу коштів на картку Приватбанку.

**Comment by AValintsev** [comment]
Add resources:
plugins.friendlyname.payments.payinstore
Оплата на картку Приватбанку

plugins.friendlyname.payments.cashondelivery
Оплата готівкою
